### ISSUE TITLE
test-client.rkt error

### ISSUE THREAD

**Issue by alejandrozf** [acarrico/wayland-protocol#1]
Hi!
I'm trying to use your program, but following your instructions I got 

the error:

"generated/wl_display-client.rkt:11:34:
 cannot open module file
  module path: #path:/home/alejandrozf/wayland-racket/examples/wayland-protocol/generated/wl_object-client.rkt
  path: /home/alejandrozf/wayland-racket/examples/wayland-protocol/generated/wl_object-client.rkt
  system error: No such file or directory; errno=2
  context...:
   standard-module-name-resolver
   standard-module-name-resolver"

when I try to execute "test-client.rkt" after create files under "generated/" folder.

It seems that the file "wl_object-client.rkt" is not being generated by "gen-wayland-protocol.rkt"?

All the best
Alejandro

**Comment by acarrico** [comment]
Just off the top of my head, I might need to know where you are getting your /usr/share/wayland/wayland.xml. For some reason, my ISP's DNS server couldn't resolve github.com, so I had a little delay looking into this (fixed). I did the readme myself a few days ago and only had some minor trouble with paths. I think I'll make a nix derivation to yield a proper environment for development.

**Comment by alejandrozf** [comment]
This is the wayland file I used [https://cgit.freedesktop.org/wayland/wayland/tree/protocol/wayland.xml?id=ae6f3001a51cce102422e4ccbeb394fe90945a12](url)

**Comment by acarrico** [comment]
Update:

My wayland.xml:

```
    <request name="bind">
      <description summary="bind an object to the display">
    Binds a new, client-created object to the server using the
        specified name as the identifier.
      </description>
      <arg name="name" type="uint" summary="unique name for the object"/>
      <arg name="id" type="new_id"/>
    </request>
```

Your wayland.xml::

```
    <request name="bind">
      <description summary="bind an object to the display">
    Binds a new, client-created object to the server using @name as
    the identifier.
      </description>
      <arg name="name" type="uint" summary="unique number id for object"/>
      <arg name="interface" type="string"/>
      <arg name="version" type="uint"/>
      <arg name="id" type="new_id" interface="wl_object"/>
    </request>
```

Note the `interface="wl_object"`

**Comment by alejandrozf** [comment]
Thanks!
I update my wayland.xml with your changes but now it shows me this error:

generated/wl_display-client.rkt:56:4: wl_object-pointer: unbound identifier in module
  in: wl_object-pointer
  context...:
   standard-module-name-resolver

could send me your complete wayland.xml? I'm really interested in contribute to this project.
My email is in my profile.
Greetings!

**Comment by acarrico** [comment]
As far as I can tell, your version of the protocol dates to this commit:

https://cgit.freedesktop.org/wayland/wayland/commit/protocol/wayland.xml?id=ae6f3001a51cce102422e4ccbeb394fe90945a12

from 2012-06-27, which predates this library.

To get usable dependencies:
1. Pull my recent changes. I've added partial nix support.
2. Install the nix package manager on any Linux distribution (https://nixos.org/nix/).
3. Now the 'nix-shell' command will use './default.nix' to pull a working racket, wayland, and weston into a sub-shell (without touching the env on the rest of your machine):
   
   $ nix-shell
4. Now source './dev.bash' (or step through by hand) to generate the racket protocol:
   
   $ source ./dev.bash
5. That generates bindings from the 'wayland.xml' file which nix pulled, BUT testing may still fail for you, since I didn't patch the racket protocol to actually use the dynamic library that nix pulled yet:
   
   $ racket test-client.rkt
6. Leaving nix-shell drops you back into your normal environment:
   
   $ exit

**Comment by acarrico** [comment]
I'll try to fix up the dynamic load path next.

**Comment by acarrico** [comment]
That work is complete. Hopefully this closes your issue.

```
commit 7ca1dbea1eafd919c1bdeb64941d35aa1fa05e8e
Author: Anthony Carrico <acarrico@memebeam.org>
Date:   Tue Oct 25 02:37:52 2016 -0400

    Configure and build with correct foreign library paths.

    Add wayland_share and wayland_lib configuration environment variables.

    New: "generated/libwayland-server.rkt"
    New: "generated/libwayland-client.rkt"

    dev.bash provides:
      * build function instead of building
      * weston-pixman function instead of starting weston.
      * wayland-test function.

    Document configure/build/test procedure in README.md.
```

**Comment by alejandrozf** [comment]
Nice!! Thanks Anthony!!
